# config.yml

model_seq: "v2.0" #for versioning
pretrained: True # Use True to load a pretrained model, False to train from scratch
pretrained_path: "./models/model_v1/best.pth"

data:
  data_dir: "Data"
  batch_size: 128
  num_workers: 4

training:
  num_epochs: 20
  patience: 5
  lr: 0.0001
  device: "cuda"  # Set to "cpu" or "cuda"